# ==============================
# SIMULADOR COMPLETO DA ENIGMA
# ==============================
import string

ALFABETO = string.ascii_uppercase

class Rotor:
    def __init__(self, wiring, notch, position=0):
            self.wiring = wiring
                    self.notch = notch
                            self.position = position

                                def rotate(self):
                                        self.position = (self.position + 1) % 26
                                                return self.position == self.notch

                                                    def forward(self, c):
                                                            index = (ALFABETO.index(c) + self.position) % 26
                                                                    letter = self.wiring[index]
                                                                            return ALFABETO[(ALFABETO.index(letter) - self.position) % 26]

                                                                                def backward(self, c):
                                                                                        index = (ALFABETO.index(c) + self.position) % 26
                                                                                                letter = ALFABETO[self.wiring.index(ALFABETO[index])]
                                                                                                        return ALFABETO[(ALFABETO.index(letter) - self.position) % 26]

                                                                                                        class Reflector:
                                                                                                            def __init__(self, wiring):
                                                                                                                    self.wiring = wiring

                                                                                                                        def reflect(self, c):
                                                                                                                                return self.wiring[ALFABETO.index(c)]

                                                                                                                                class Plugboard:
                                                                                                                                    def __init__(self, connections=None):
                                                                                                                                            self.mapping = {c: c for c in ALFABETO}
                                                                                                                                                    if connections:
                                                                                                                                                                for pair in connections:
                                                                                                                                                                                a, b = pair[0], pair[1]
                                                                                                                                                                                                self.mapping[a] = b
                                                                                                                                                                                                                self.mapping[b] = a

                                                                                                                                                                                                                    def swap(self, c):
                                                                                                                                                                                                                            return self.mapping[c]

                                                                                                                                                                                                                            class Enigma:
                                                                                                                                                                                                                                def __init__(self, rotor1, rotor2, rotor3, reflector, plugboard=None):
                                                                                                                                                                                                                                        self.rotor1 = rotor1
                                                                                                                                                                                                                                                self.rotor2 = rotor2
                                                                                                                                                                                                                                                        self.rotor3 = rotor3
                                                                                                                                                                                                                                                                self.reflector = reflector
                                                                                                                                                                                                                                                                        self.plugboard = plugboard if plugboard else Plugboard()

                                                                                                                                                                                                                                                                            def encrypt_letter(self, c):
                                                                                                                                                                                                                                                                                    if c not in ALFABETO:
                                                                                                                                                                                                                                                                                                return c
                                                                                                                                                                                                                                                                                                        if self.rotor1.rotate():
                                                                                                                                                                                                                                                                                                                    if self.rotor2.rotate():
                                                                                                                                                                                                                                                                                                                                    self.rotor3.rotate()
                                                                                                                                                                                                                                                                                                                                            c = self.plugboard.swap(c)
                                                                                                                                                                                                                                                                                                                                                    c = self.rotor1.forward(c)
                                                                                                                                                                                                                                                                                                                                                            c = self.rotor2.forward(c)
                                                                                                                                                                                                                                                                                                                                                                    c = self.rotor3.forward(c)
                                                                                                                                                                                                                                                                                                                                                                            c = self.reflector.reflect(c)
                                                                                                                                                                                                                                                                                                                                                                                    c = self.rotor3.backward(c)
                                                                                                                                                                                                                                                                                                                                                                                            c = self.rotor2.backward(c)
                                                                                                                                                                                                                                                                                                                                                                                                    c = self.rotor1.backward(c)
                                                                                                                                                                                                                                                                                                                                                                                                            c = self.plugboard.swap(c)
                                                                                                                                                                                                                                                                                                                                                                                                                    return c

                                                                                                                                                                                                                                                                                                                                                                                                                        def encrypt(self, text):
                                                                                                                                                                                                                                                                                                                                                                                                                                result = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                        for char in text.upper():
                                                                                                                                                                                                                                                                                                                                                                                                                                                    result += self.encrypt_letter(char)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return result

                                                                                                                                                                                                                                                                                                                                                                                                                                                            rotor_I   = Rotor("EKMFLGDQVZNTOWYHXUSPAIBRCJ", notch=16)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            rotor_II  = Rotor("AJDKSIRUXBLHWTMCQGZNPYFVOE", notch=4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            rotor_III = Rotor("BDFHJLCPRTXVZNYEIWGAKMUSQO", notch=21)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            reflector_B = Reflector("YRUHQSLDPXNGOKMIEBFZCWVJAT")
                                                                                                                                                                                                                                                                                                                                                                                                                                                            plugboard = Plugboard(["AB", "CD", "EF"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                            enigma = Enigma(rotor_I, rotor_II, rotor_III, reflector_B, plugboard)

                                                                                                                                                                                                                                                                                                                                                                                                                                                            mensagem = "ATAQUE AO AMANHECER"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            criptografada = enigma.encrypt(mensagem)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Mensagem original:", mensagem)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Mensagem apos criptografia:", criptografada)
